### PR TITLE
Fix js enable/disable links to point to master

### PR DESCRIPTION
**Pull request by learningcljs**

### CODE REVIEW

**Comment by magomimmo** [comment]
you're prolific this days :-). thanks!

**Comment by learningcljs** [comment]
Thanks again for making the tutorial series.

I am new to using Github as well as CLJS.  So I am happy that I am able to contribute to your tutorial series as it let's me learn how to use Github while I am working through the tutorial series.

I am open to suggestions on how to be a better Github contributor if you have any that you would like to share.

**Comment by magomimmo** [comment]
at the moment you're doing pretty well! You could eventually make the life easier for the owner of a repo by rebasing more commits in one: http://stackoverflow.com/search?q=rebase

**Comment by learningcljs** [comment]
Thanks for the suggestion.

**Pull request merged**
