### PR TITLE
Update tutorial-03.md

### PR DESCRIPTION
**Pull request by magopian**
Seems this one isn't complete yet (the links aren't correct, I tried to correct them).

I can't wait for the next one! What's the best way for me to know when there's a new one you're working on (or at least, a new one you'd like to have proof-reading?)

### CODE REVIEW

**Comment by magomimmo** [comment]
the problem is that I work on different computers in different location which means that I use the modern-cljs repository as a temporary workspace as well by commiting the second-edition brach even when is not ready at all. If watch the repo you should receive notification about my commits, but this does not mean that the committed tutorials are ready to be used. I'd like to wait to make them available until at lest 5/6 of them are stable enough in my mind....

cheers

**Comment by magopian** [comment]
Well, if you want to, just drop me an email whenever you'd like someone to give it a look and try it out ;)

I won't be able to tell you if there's a better way to do it, though, because i'm just a beginner!

Happy to help anyway

**Comment by magomimmo** [comment]
Hi Mathieu, if you want to take a look, here is the draft...

https://github.com/magomimmo/modern-cljs/blob/second-edition/doc/tutorial-03.md

cheers

**Comment by magopian** [comment]
Thanks! You can close this PR if you want :)

**Pull request closed without merging**
