### PR TITLE
Add tdd and bdd references

### PR DESCRIPTION
**Pull request by learningcljs**
I'm not sure why it is saying:
> Can’t automatically merge

I hope this is not the same issue as pull request #337.

When I look at the branch it says that it is 0 commits behind master.

I have been learning Github as I have making contributions to `modern-cljs`.  So I have been relying more on the Github user interface than on `git` in the terminal.  Now that I feel more comfortable with Github I plan to improve my use of `git` so that I can hopefully avoid these types of issues.

### CODE REVIEW

**Comment by magomimmo** [comment]
probably you did not update your master with the upstream master  before doing your work....

**Comment by learningcljs** [comment]
It is time for me to learn how to use `git ` better.

**Comment by magomimmo** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by magomimmo** [comment]
I usually do this way:

1. fork a repo
2. locally clone the fork `git clone https://....`
3 add the upstream

```bash
cd <cloned-repo>
git remote add upstream https://<upstream-repo-address
```
4. update the local clone from the upstream `git fetch upstream`
5. merge the update `git merge upstream/master`
6. push the local updated repo to the fork `git push origin master'

This way I always have the latest updates from the upstream both locally and on github and I start contributing. 

HIH
mimmo

**Comment by learningcljs** [comment]
Thanks that is helpful.
I have also been learning more about git so I can use it better.

I am closing this pull request.
I will retry the pull request using `git` instead of the `github` user interface.

**Pull request closed without merging**
