### PR TITLE
Update tutorial-05.md

### PR DESCRIPTION
**Pull request by magopian**
Minor typos

### CODE REVIEW

**Comment by magopian** [comment]
I'm loving this tutorial, really detailed, step by step, easy to follow, and it helps me with topics I kept struggling with. THIS IS AWESOME, thanks a lot @magomimmo! Keep up the good work!

**Comment by magomimmo** [comment]
Thanks @magopian. Just take into account that the next edition I just started working on will use `boot` instead of leiningen. It will take time, but our life as clojurescript programmers will be easier

**Comment by magopian** [comment]
Excellent news, I'll be checking this page often then ;)

**Comment by magomimmo** [comment]
the very draft of tutorial-01. I did not even re-read it….

https://github.com/magomimmo/modern-cljs/blob/second-edition/doc/tutorial-01.md <https://github.com/magomimmo/modern-cljs/blob/second-edition/doc/tutorial-01.md>

cheers
mimmo

**Comment by magopian** [comment]
Looks very promising! Apart from the `bla bla bla` in the `Install Boot` section (just joking ;)

Thanks again for all this work! Very useful!

**Pull request merged**
