### PR TITLE
Fix bREPL typos, links and other minor edits

### PR DESCRIPTION
**Pull request by learningcljs**

### CODE REVIEW

**Comment by magomimmo** [comment]
thanks! The next part is going to be tuff :-)

**Comment by learningcljs** [comment]
For the next part on reactive state were you thinking of porting over more of the React tutorial such as these sections?

- [Reactive state](https://facebook.github.io/react/docs/tutorial.html#reactive-state)
- [Adding new comments](https://facebook.github.io/react/docs/tutorial.html#adding-new-comments)

I've read through the [re-frame README](https://github.com/Day8/re-frame/blob/master/README.md) and it looks like `re-frame` could be useful for dealing with reactive state.  Where you considering using `re-frame` or another library or framework in addition to `Reagent` in this reactive state section?

**Comment by magomimmo** [comment]
Sure. The only thing I'm not going to port, because is not useful for understanding the state management in Reagent, is the ajax polling from the server. re-frame is just wonderful, but in React Tutorial can be very easily ported to Reagent by using Reagent only.

**Comment by learningcljs** [comment]
I just wanted to clarify that with this:

>For the next part on reactive state were you thinking of porting over more of the React tutorial such as these sections?
- [Reactive state](https://facebook.github.io/react/docs/tutorial.html#reactive-state)
- [Adding new comments](https://facebook.github.io/react/docs/tutorial.html#adding-new-comments)

my intention was not to request specific content but was rather me ask what was planned for the next part of this interesting tutorial and guessing at the same time.

**Comment by magomimmo** [comment]
Yep, I understand. I just added a couple of new paragraphs. Perhaps this tutorial is going to be longer than the others. Probably we should break it down in two pieces....

**Comment by learningcljs** [comment]
The start of the [Reactive state](https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-21b.md#reactive-state) section looks like a decent place to split it if it is going to span two tutorials.

If you let me know when the second half of this is stabalized I will work through it then.

**Comment by magomimmo** [comment]
yes. I did as you said. I let you know when I'll be ready with part II on state management....

**Comment by magomimmo** [comment]
@learningcljs I did some work today...If you don't mind to take a look, I appreciate. Still to complete the tutorial with a paragraph on creating new comments....

**Comment by learningcljs** [comment]
I worked through the Reagent tutorials 21 and 22.
Pull request #361 offers some minor edits for these.

**Comment by magomimmo** [comment]
great. thanks.

**Pull request merged**
